export default {
    editor: {
        label: { en: 'Admin Panel', pl: 'Panel administracyjny' },
        icon: 'settings',
        customStylePropertiesOrder: [
            ['supabaseUrl', 'supabaseAnonKey'],
            ['showSidebar', 'sidebarWidth', 'sidebarBgColor', 'sidebarBorderColor'],
            ['contentPadding', 'contentMaxWidth'],
            ['accentColor', 'accentHoverColor', 'bgColor', 'cardBgColor', 'cardBorderRadius'],
            ['borderColor', 'borderLightColor'],
            ['textColor', 'textMutedColor', 'textHintColor'],
            ['titleFontSize', 'titleFontWeight', 'bodyFontSize', 'smallFontSize', 'fontFamily'],
            ['badgeFontSize', 'badgePadding', 'badgeBorderRadius'],
            ['inputBgColor', 'inputBorderColor', 'inputFocusBorderColor', 'inputBorderRadius', 'inputPadding', 'inputFontSize'],
            ['btnPrimaryBg', 'btnPrimaryText', 'btnSecondaryBg', 'btnSecondaryText', 'btnBorderRadius', 'btnPadding', 'btnFontSize'],
            ['tableHeaderBg', 'tableRowHoverBg', 'tableRowSelectedBg', 'tableRowBorderColor'],
            ['statusActiveColor', 'statusInactiveColor', 'statusTerminatedColor', 'statusVacationColor'],
            ['overlayBgColor', 'panelWidth', 'panelBgColor'],
            ['modalBgColor', 'modalBorderRadius', 'modalMaxWidth', 'modalPadding'],
            ['toastSuccessBg', 'toastSuccessText', 'toastErrorBg', 'toastErrorText', 'toastInfoBg', 'toastInfoText'],
            ['animationDuration', 'animationEasing'],
            ['spacingXs', 'spacingSm', 'spacingMd', 'spacingLg', 'spacingXl'],
            ['auditAutoRefresh', 'auditRefreshInterval']
        ]
    },
    properties: {
        supabaseUrl: { label: { en: 'Supabase URL', pl: 'Supabase URL' }, type: 'Text', defaultValue: '', bindable: true, section: 'settings' },
        supabaseAnonKey: { label: { en: 'Supabase Anon Key', pl: 'Supabase Anon Key' }, type: 'Text', defaultValue: '', bindable: true, section: 'settings' },
        showSidebar: { label: { en: 'Show Sidebar', pl: 'Pokaż sidebar' }, type: 'OnOff', defaultValue: true, bindable: true, responsive: true },
        sidebarWidth: { label: { en: 'Sidebar Width', pl: 'Szerokość sidebara' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 140, max: 400 }] }, defaultValue: '220px', bindable: true, responsive: true },
        sidebarBgColor: { label: { en: 'Sidebar Background', pl: 'Tło sidebara' }, type: 'Color', defaultValue: '#161616', bindable: true, responsive: true },
        sidebarBorderColor: { label: { en: 'Sidebar Border', pl: 'Ramka sidebara' }, type: 'Color', defaultValue: '#2a2a28', bindable: true, responsive: true },
        contentPadding: { label: { en: 'Content Padding', pl: 'Padding treści' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 8, max: 80 }] }, defaultValue: '32px', bindable: true, responsive: true },
        contentMaxWidth: { label: { en: 'Content Max Width', pl: 'Max szer. treści' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 600, max: 2000 }] }, defaultValue: '1100px', bindable: true, responsive: true },
        accentColor: { label: { en: 'Accent Color', pl: 'Kolor akcentu' }, type: 'Color', defaultValue: '#6366f1', bindable: true, responsive: true },
        accentHoverColor: { label: { en: 'Accent Hover', pl: 'Akcent hover' }, type: 'Color', defaultValue: 'rgba(99,102,241,0.12)', bindable: true, responsive: true },
        bgColor: { label: { en: 'Background', pl: 'Tło' }, type: 'Color', defaultValue: '#0f0f0f', bindable: true, responsive: true },
        cardBgColor: { label: { en: 'Card Background', pl: 'Tło kart' }, type: 'Color', defaultValue: '#1c1c1c', bindable: true, responsive: true },
        cardBorderRadius: { label: { en: 'Card Radius', pl: 'Zaokrąglenie kart' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 24 }] }, defaultValue: '12px', bindable: true, responsive: true },
        borderColor: { label: { en: 'Border Color', pl: 'Kolor ramek' }, type: 'Color', defaultValue: '#2a2a28', bindable: true, responsive: true },
        borderLightColor: { label: { en: 'Light Border', pl: 'Lekka ramka' }, type: 'Color', defaultValue: 'rgba(255,255,255,0.02)', bindable: true, responsive: true },
        textColor: { label: { en: 'Text Color', pl: 'Kolor tekstu' }, type: 'Color', defaultValue: '#e8e6e1', bindable: true, responsive: true },
        textMutedColor: { label: { en: 'Muted Text', pl: 'Wyciszony' }, type: 'Color', defaultValue: '#8a8880', bindable: true, responsive: true },
        textHintColor: { label: { en: 'Hint Text', pl: 'Podpowiedź' }, type: 'Color', defaultValue: '#5a5950', bindable: true, responsive: true },
        titleFontSize: { label: { en: 'Title Size', pl: 'Rozmiar tytułu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 16, max: 40 }] }, defaultValue: '24px', bindable: true, responsive: true },
        titleFontWeight: { label: { en: 'Title Weight', pl: 'Grubość tytułu' }, type: 'TextSelect', options: { options: [{ value: '400', label: { en: 'Regular' } }, { value: '500', label: { en: 'Medium' } }, { value: '600', label: { en: 'Semi Bold' } }, { value: '700', label: { en: 'Bold' } }] }, defaultValue: '700', bindable: true, responsive: true },
        bodyFontSize: { label: { en: 'Body Size', pl: 'Tekst' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 10, max: 20 }] }, defaultValue: '13px', bindable: true, responsive: true },
        smallFontSize: { label: { en: 'Small Size', pl: 'Mały tekst' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 8, max: 16 }] }, defaultValue: '11px', bindable: true, responsive: true },
        fontFamily: { label: { en: 'Font Family', pl: 'Czcionka' }, type: 'Text', defaultValue: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", bindable: true },
        badgeFontSize: { label: { en: 'Badge Size', pl: 'Badge' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 8, max: 16 }] }, defaultValue: '11px', bindable: true, responsive: true },
        badgePadding: { label: { en: 'Badge Padding', pl: 'Padding badge' }, type: 'Text', defaultValue: '3px 10px', bindable: true },
        badgeBorderRadius: { label: { en: 'Badge Radius', pl: 'Zaokrąglenie badge' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 30 }] }, defaultValue: '20px', bindable: true, responsive: true },
        inputBgColor: { label: { en: 'Input BG', pl: 'Tło inputu' }, type: 'Color', defaultValue: '#1c1c1c', bindable: true, responsive: true },
        inputBorderColor: { label: { en: 'Input Border', pl: 'Ramka inputu' }, type: 'Color', defaultValue: '#2a2a28', bindable: true, responsive: true },
        inputFocusBorderColor: { label: { en: 'Input Focus', pl: 'Focus inputu' }, type: 'Color', defaultValue: '#6366f1', bindable: true, responsive: true },
        inputBorderRadius: { label: { en: 'Input Radius', pl: 'Zaokr. inputu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 20 }] }, defaultValue: '8px', bindable: true, responsive: true },
        inputPadding: { label: { en: 'Input Padding', pl: 'Padding inputu' }, type: 'Text', defaultValue: '10px 14px', bindable: true },
        inputFontSize: { label: { en: 'Input Font', pl: 'Tekst inputu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 10, max: 18 }] }, defaultValue: '13px', bindable: true, responsive: true },
        btnPrimaryBg: { label: { en: 'Btn Primary BG', pl: 'Tło przycisku' }, type: 'Color', defaultValue: '#6366f1', bindable: true, responsive: true },
        btnPrimaryText: { label: { en: 'Btn Primary Text', pl: 'Tekst przycisku' }, type: 'Color', defaultValue: '#ffffff', bindable: true, responsive: true },
        btnSecondaryBg: { label: { en: 'Btn Secondary BG', pl: 'Tło 2-go' }, type: 'Color', defaultValue: '#1c1c1c', bindable: true, responsive: true },
        btnSecondaryText: { label: { en: 'Btn Secondary Text', pl: 'Tekst 2-go' }, type: 'Color', defaultValue: '#e8e6e1', bindable: true, responsive: true },
        btnBorderRadius: { label: { en: 'Btn Radius', pl: 'Zaokr. przycisków' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 20 }] }, defaultValue: '8px', bindable: true, responsive: true },
        btnPadding: { label: { en: 'Btn Padding', pl: 'Padding przycisków' }, type: 'Text', defaultValue: '8px 14px', bindable: true },
        btnFontSize: { label: { en: 'Btn Font', pl: 'Tekst przycisków' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 10, max: 18 }] }, defaultValue: '12px', bindable: true, responsive: true },
        tableHeaderBg: { label: { en: 'Table Header BG', pl: 'Tło nagłówka' }, type: 'Color', defaultValue: 'transparent', bindable: true, responsive: true },
        tableRowHoverBg: { label: { en: 'Row Hover', pl: 'Hover wiersza' }, type: 'Color', defaultValue: 'rgba(99,102,241,0.06)', bindable: true, responsive: true },
        tableRowSelectedBg: { label: { en: 'Row Selected', pl: 'Wybrany wiersz' }, type: 'Color', defaultValue: 'rgba(99,102,241,0.12)', bindable: true, responsive: true },
        tableRowBorderColor: { label: { en: 'Row Border', pl: 'Ramka wiersza' }, type: 'Color', defaultValue: 'rgba(255,255,255,0.02)', bindable: true, responsive: true },
        statusActiveColor: { label: { en: 'Active', pl: 'Aktywny' }, type: 'Color', defaultValue: '#22c55e', bindable: true, responsive: true },
        statusInactiveColor: { label: { en: 'Inactive', pl: 'Nieaktywny' }, type: 'Color', defaultValue: '#eab308', bindable: true, responsive: true },
        statusTerminatedColor: { label: { en: 'Terminated', pl: 'Zwolniony' }, type: 'Color', defaultValue: '#ef4444', bindable: true, responsive: true },
        statusVacationColor: { label: { en: 'Vacation', pl: 'Urlop' }, type: 'Color', defaultValue: '#6366f1', bindable: true, responsive: true },
        overlayBgColor: { label: { en: 'Overlay BG', pl: 'Tło overlay' }, type: 'Color', defaultValue: 'rgba(0,0,0,0.6)', bindable: true, responsive: true },
        panelWidth: { label: { en: 'Panel Width', pl: 'Szer. panelu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 300, max: 800 }] }, defaultValue: '540px', bindable: true, responsive: true },
        panelBgColor: { label: { en: 'Panel BG', pl: 'Tło panelu' }, type: 'Color', defaultValue: '#1c1c1c', bindable: true, responsive: true },
        modalBgColor: { label: { en: 'Modal BG', pl: 'Tło modalu' }, type: 'Color', defaultValue: '#1c1c1c', bindable: true, responsive: true },
        modalBorderRadius: { label: { en: 'Modal Radius', pl: 'Zaokr. modalu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 30 }] }, defaultValue: '16px', bindable: true, responsive: true },
        modalMaxWidth: { label: { en: 'Modal Width', pl: 'Szer. modalu' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 300, max: 800 }] }, defaultValue: '560px', bindable: true, responsive: true },
        modalPadding: { label: { en: 'Modal Padding', pl: 'Padding modalu' }, type: 'Text', defaultValue: '24px', bindable: true },
        toastSuccessBg: { label: { en: 'Toast OK BG' }, type: 'Color', defaultValue: '#065f46', bindable: true },
        toastSuccessText: { label: { en: 'Toast OK Text' }, type: 'Color', defaultValue: '#a7f3d0', bindable: true },
        toastErrorBg: { label: { en: 'Toast Err BG' }, type: 'Color', defaultValue: '#7f1d1d', bindable: true },
        toastErrorText: { label: { en: 'Toast Err Text' }, type: 'Color', defaultValue: '#fca5a5', bindable: true },
        toastInfoBg: { label: { en: 'Toast Info BG' }, type: 'Color', defaultValue: '#1e3a5f', bindable: true },
        toastInfoText: { label: { en: 'Toast Info Text' }, type: 'Color', defaultValue: '#93c5fd', bindable: true },
        animationDuration: { label: { en: 'Anim Duration', pl: 'Czas animacji' }, type: 'Length', options: { unitChoices: [{ value: 'ms', label: 'ms', min: 0, max: 1000 }] }, defaultValue: '200ms', bindable: true, responsive: true },
        animationEasing: { label: { en: 'Anim Easing', pl: 'Easing' }, type: 'TextSelect', options: { options: [{ value: 'ease', label: { en: 'ease' } }, { value: 'ease-out', label: { en: 'ease-out' } }, { value: 'ease-in-out', label: { en: 'ease-in-out' } }, { value: 'linear', label: { en: 'linear' } }, { value: 'cubic-bezier(0.16,1,0.3,1)', label: { en: 'smooth' } }] }, defaultValue: 'ease-out', bindable: true, responsive: true },
        spacingXs: { label: { en: 'Space XS' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 16 }] }, defaultValue: '4px', bindable: true, responsive: true },
        spacingSm: { label: { en: 'Space SM' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 24 }] }, defaultValue: '8px', bindable: true, responsive: true },
        spacingMd: { label: { en: 'Space MD' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 40 }] }, defaultValue: '16px', bindable: true, responsive: true },
        spacingLg: { label: { en: 'Space LG' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 60 }] }, defaultValue: '24px', bindable: true, responsive: true },
        spacingXl: { label: { en: 'Space XL' }, type: 'Length', options: { unitChoices: [{ value: 'px', label: 'px', min: 0, max: 80 }] }, defaultValue: '32px', bindable: true, responsive: true },
        auditAutoRefresh: { label: { en: 'Audit Auto-Refresh', pl: 'Auto-odświeżanie audytu' }, type: 'OnOff', defaultValue: true, bindable: true },
        auditRefreshInterval: { label: { en: 'Refresh Interval (sec)', pl: 'Interwał (sek)' }, type: 'Number', options: { min: 1, max: 60, step: 1 }, defaultValue: 3, bindable: true },
    }
};
