export default {
    editor: {
        label: { en: 'Admin Panel', pl: 'Panel administracyjny' },
        icon: 'settings',
        customStylePropertiesOrder: [
            ['supabaseUrl', 'supabaseAnonKey'],
            ['showSidebar','sidebarWidth','sidebarBgColor','sidebarBorderColor'],
            ['navActiveColor','navActiveBg','navInactiveColor','navHoverBg'],
            ['contentPadding','contentMaxWidth'],
            ['accentColor','accentHoverColor','bgColor','cardBgColor','cardBorderRadius'],
            ['borderColor','borderLightColor'],
            ['textColor','textMutedColor','textHintColor'],
            ['titleFontSize','titleFontWeight','bodyFontSize','smallFontSize','fontFamily'],
            ['badgeFontSize','badgePadding','badgeBorderRadius'],
            ['inputBgColor','inputBorderColor','inputFocusBorderColor','inputBorderRadius','inputPadding','inputFontSize'],
            ['selectBgColor','selectTextColor','selectBorderColor','selectFontSize','selectOptionBg','selectOptionText'],
            ['btnPrimaryBg','btnPrimaryText','btnSecondaryBg','btnSecondaryText','btnBorderRadius','btnPadding','btnFontSize'],
            ['tableHeaderBg','tableRowHoverBg','tableRowSelectedBg','tableRowBorderColor'],
            ['statusActiveColor','statusInactiveColor','statusTerminatedColor','statusVacationColor'],
            ['overlayBgColor','panelWidth','panelBgColor'],
            ['modalBgColor','modalBorderRadius','modalMaxWidth','modalPadding'],
            ['toastSuccessBg','toastSuccessText','toastErrorBg','toastErrorText','toastInfoBg','toastInfoText'],
            ['animationDuration','animationEasing'],
            ['spacingXs','spacingSm','spacingMd','spacingLg','spacingXl'],
            ['auditAutoRefresh','auditRefreshInterval'],
            ['labelDashboard','labelUsers','labelRoles','labelAudit','labelTemp'],
            ['labelBtnCopy','labelBtnAddRole','labelBtnTempAccess','labelBtnNewRole','labelBtnApply','labelBtnApplyModified'],
            ['labelSearch','labelAllRoles','labelNoResults','labelSuperAdmin','labelVacation'],
            ['labelTabRoles','labelTabVisibility','labelAssignedRoles','labelPermissions','labelVisibleClients'],
            ['labelTempType','labelTempRole','labelTempDept','labelTempExpires','labelTempReason','labelTempApply'],
            ['labelAuditAllTables','labelAuditEmailPlaceholder'],
            ['labelConfirmDeleteRole','labelConfirmRemoveRole','labelConfirmRevoke']
        ]
    },
    properties: {
        supabaseUrl: { label:{en:'Supabase URL'}, type:'Text', defaultValue:'', bindable:true, section:'settings' },
        supabaseAnonKey: { label:{en:'Supabase Anon Key'}, type:'Text', defaultValue:'', bindable:true, section:'settings' },
        showSidebar: { label:{en:'Show Sidebar'}, type:'OnOff', defaultValue:true, bindable:true, responsive:true },
        sidebarWidth: { label:{en:'Sidebar Width'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:140,max:400}]}, defaultValue:'220px', bindable:true, responsive:true },
        sidebarBgColor: { label:{en:'Sidebar BG'}, type:'Color', defaultValue:'#161616', bindable:true, responsive:true },
        sidebarBorderColor: { label:{en:'Sidebar Border'}, type:'Color', defaultValue:'#2a2a28', bindable:true, responsive:true },
        navActiveColor: { label:{en:'Nav Active Text'}, type:'Color', defaultValue:'#6366f1', bindable:true, responsive:true },
        navActiveBg: { label:{en:'Nav Active BG'}, type:'Color', defaultValue:'rgba(99,102,241,0.12)', bindable:true, responsive:true },
        navInactiveColor: { label:{en:'Nav Inactive Text'}, type:'Color', defaultValue:'#8a8880', bindable:true, responsive:true },
        navHoverBg: { label:{en:'Nav Hover BG'}, type:'Color', defaultValue:'rgba(99,102,241,0.06)', bindable:true, responsive:true },
        contentPadding: { label:{en:'Content Padding'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:8,max:80}]}, defaultValue:'32px', bindable:true, responsive:true },
        contentMaxWidth: { label:{en:'Content Max W'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:600,max:2000}]}, defaultValue:'1100px', bindable:true, responsive:true },
        accentColor: { label:{en:'Accent'}, type:'Color', defaultValue:'#6366f1', bindable:true, responsive:true },
        accentHoverColor: { label:{en:'Accent Hover'}, type:'Color', defaultValue:'rgba(99,102,241,0.12)', bindable:true, responsive:true },
        bgColor: { label:{en:'Background'}, type:'Color', defaultValue:'#0f0f0f', bindable:true, responsive:true },
        cardBgColor: { label:{en:'Card BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true, responsive:true },
        cardBorderRadius: { label:{en:'Card Radius'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:24}]}, defaultValue:'12px', bindable:true, responsive:true },
        borderColor: { label:{en:'Border'}, type:'Color', defaultValue:'#2a2a28', bindable:true, responsive:true },
        borderLightColor: { label:{en:'Light Border'}, type:'Color', defaultValue:'rgba(255,255,255,0.02)', bindable:true, responsive:true },
        textColor: { label:{en:'Text'}, type:'Color', defaultValue:'#e8e6e1', bindable:true, responsive:true },
        textMutedColor: { label:{en:'Muted'}, type:'Color', defaultValue:'#8a8880', bindable:true, responsive:true },
        textHintColor: { label:{en:'Hint'}, type:'Color', defaultValue:'#5a5950', bindable:true, responsive:true },
        titleFontSize: { label:{en:'Title Size'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:16,max:40}]}, defaultValue:'24px', bindable:true, responsive:true },
        titleFontWeight: { label:{en:'Title Weight'}, type:'TextSelect', options:{options:[{value:'400',label:{en:'Regular'}},{value:'500',label:{en:'Medium'}},{value:'600',label:{en:'Semi Bold'}},{value:'700',label:{en:'Bold'}}]}, defaultValue:'700', bindable:true, responsive:true },
        bodyFontSize: { label:{en:'Body Size'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:10,max:20}]}, defaultValue:'13px', bindable:true, responsive:true },
        smallFontSize: { label:{en:'Small Size'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:8,max:16}]}, defaultValue:'11px', bindable:true, responsive:true },
        fontFamily: { label:{en:'Font'}, type:'Text', defaultValue:"-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif", bindable:true },
        badgeFontSize: { label:{en:'Badge Size'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:8,max:16}]}, defaultValue:'11px', bindable:true, responsive:true },
        badgePadding: { label:{en:'Badge Pad'}, type:'Text', defaultValue:'3px 10px', bindable:true },
        badgeBorderRadius: { label:{en:'Badge Radius'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:30}]}, defaultValue:'20px', bindable:true, responsive:true },
        inputBgColor: { label:{en:'Input BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true, responsive:true },
        inputBorderColor: { label:{en:'Input Border'}, type:'Color', defaultValue:'#2a2a28', bindable:true, responsive:true },
        inputFocusBorderColor: { label:{en:'Input Focus'}, type:'Color', defaultValue:'#6366f1', bindable:true, responsive:true },
        inputBorderRadius: { label:{en:'Input Radius'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:20}]}, defaultValue:'8px', bindable:true, responsive:true },
        inputPadding: { label:{en:'Input Pad'}, type:'Text', defaultValue:'10px 14px', bindable:true },
        inputFontSize: { label:{en:'Input Font'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:10,max:18}]}, defaultValue:'13px', bindable:true, responsive:true },
        selectBgColor: { label:{en:'Select BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true, responsive:true },
        selectTextColor: { label:{en:'Select Text'}, type:'Color', defaultValue:'#e8e6e1', bindable:true, responsive:true },
        selectBorderColor: { label:{en:'Select Border'}, type:'Color', defaultValue:'#2a2a28', bindable:true, responsive:true },
        selectFontSize: { label:{en:'Select Font'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:10,max:18}]}, defaultValue:'13px', bindable:true, responsive:true },
        selectOptionBg: { label:{en:'Option BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true },
        selectOptionText: { label:{en:'Option Text'}, type:'Color', defaultValue:'#e8e6e1', bindable:true },
        btnPrimaryBg: { label:{en:'Btn BG'}, type:'Color', defaultValue:'#6366f1', bindable:true, responsive:true },
        btnPrimaryText: { label:{en:'Btn Text'}, type:'Color', defaultValue:'#ffffff', bindable:true, responsive:true },
        btnSecondaryBg: { label:{en:'Btn2 BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true, responsive:true },
        btnSecondaryText: { label:{en:'Btn2 Text'}, type:'Color', defaultValue:'#e8e6e1', bindable:true, responsive:true },
        btnBorderRadius: { label:{en:'Btn Radius'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:20}]}, defaultValue:'8px', bindable:true, responsive:true },
        btnPadding: { label:{en:'Btn Pad'}, type:'Text', defaultValue:'8px 14px', bindable:true },
        btnFontSize: { label:{en:'Btn Font'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:10,max:18}]}, defaultValue:'12px', bindable:true, responsive:true },
        tableHeaderBg: { label:{en:'Header BG'}, type:'Color', defaultValue:'transparent', bindable:true, responsive:true },
        tableRowHoverBg: { label:{en:'Row Hover'}, type:'Color', defaultValue:'rgba(99,102,241,0.06)', bindable:true, responsive:true },
        tableRowSelectedBg: { label:{en:'Row Selected'}, type:'Color', defaultValue:'rgba(99,102,241,0.12)', bindable:true, responsive:true },
        tableRowBorderColor: { label:{en:'Row Border'}, type:'Color', defaultValue:'rgba(255,255,255,0.02)', bindable:true, responsive:true },
        statusActiveColor: { label:{en:'Active'}, type:'Color', defaultValue:'#22c55e', bindable:true },
        statusInactiveColor: { label:{en:'Inactive'}, type:'Color', defaultValue:'#eab308', bindable:true },
        statusTerminatedColor: { label:{en:'Terminated'}, type:'Color', defaultValue:'#ef4444', bindable:true },
        statusVacationColor: { label:{en:'Vacation'}, type:'Color', defaultValue:'#6366f1', bindable:true },
        overlayBgColor: { label:{en:'Overlay BG'}, type:'Color', defaultValue:'rgba(0,0,0,0.6)', bindable:true },
        panelWidth: { label:{en:'Panel W'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:300,max:800}]}, defaultValue:'540px', bindable:true, responsive:true },
        panelBgColor: { label:{en:'Panel BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true },
        modalBgColor: { label:{en:'Modal BG'}, type:'Color', defaultValue:'#1c1c1c', bindable:true },
        modalBorderRadius: { label:{en:'Modal Radius'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:30}]}, defaultValue:'16px', bindable:true },
        modalMaxWidth: { label:{en:'Modal W'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:300,max:800}]}, defaultValue:'560px', bindable:true },
        modalPadding: { label:{en:'Modal Pad'}, type:'Text', defaultValue:'24px', bindable:true },
        toastSuccessBg: { label:{en:'Toast OK BG'}, type:'Color', defaultValue:'#065f46', bindable:true },
        toastSuccessText: { label:{en:'Toast OK Text'}, type:'Color', defaultValue:'#a7f3d0', bindable:true },
        toastErrorBg: { label:{en:'Toast Err BG'}, type:'Color', defaultValue:'#7f1d1d', bindable:true },
        toastErrorText: { label:{en:'Toast Err Text'}, type:'Color', defaultValue:'#fca5a5', bindable:true },
        toastInfoBg: { label:{en:'Toast Info BG'}, type:'Color', defaultValue:'#1e3a5f', bindable:true },
        toastInfoText: { label:{en:'Toast Info Text'}, type:'Color', defaultValue:'#93c5fd', bindable:true },
        animationDuration: { label:{en:'Anim Duration'}, type:'Length', options:{unitChoices:[{value:'ms',label:'ms',min:0,max:1000}]}, defaultValue:'200ms', bindable:true },
        animationEasing: { label:{en:'Easing'}, type:'TextSelect', options:{options:[{value:'ease',label:{en:'ease'}},{value:'ease-out',label:{en:'ease-out'}},{value:'ease-in-out',label:{en:'ease-in-out'}},{value:'linear',label:{en:'linear'}},{value:'cubic-bezier(0.16,1,0.3,1)',label:{en:'smooth'}}]}, defaultValue:'ease-out', bindable:true },
        spacingXs: { label:{en:'XS'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:16}]}, defaultValue:'4px', bindable:true, responsive:true },
        spacingSm: { label:{en:'SM'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:24}]}, defaultValue:'8px', bindable:true, responsive:true },
        spacingMd: { label:{en:'MD'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:40}]}, defaultValue:'16px', bindable:true, responsive:true },
        spacingLg: { label:{en:'LG'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:60}]}, defaultValue:'24px', bindable:true, responsive:true },
        spacingXl: { label:{en:'XL'}, type:'Length', options:{unitChoices:[{value:'px',label:'px',min:0,max:80}]}, defaultValue:'32px', bindable:true, responsive:true },
        auditAutoRefresh: { label:{en:'Auto-Refresh'}, type:'OnOff', defaultValue:true, bindable:true },
        auditRefreshInterval: { label:{en:'Refresh (sec)'}, type:'Number', options:{min:1,max:60,step:1}, defaultValue:3, bindable:true },
        // === CUSTOMIZABLE LABELS ===
        labelDashboard: { label:{en:'Label: Dashboard'}, type:'Text', defaultValue:'Dashboard', bindable:true },
        labelUsers: { label:{en:'Label: Users'}, type:'Text', defaultValue:'Użytkownicy', bindable:true },
        labelRoles: { label:{en:'Label: Roles'}, type:'Text', defaultValue:'Role', bindable:true },
        labelAudit: { label:{en:'Label: Audit'}, type:'Text', defaultValue:'Audyt', bindable:true },
        labelTemp: { label:{en:'Label: Temporary'}, type:'Text', defaultValue:'Tymczasowe', bindable:true },
        labelBtnCopy: { label:{en:'Btn: Copy Perms'}, type:'Text', defaultValue:'Kopiuj uprawnienia na...', bindable:true },
        labelBtnAddRole: { label:{en:'Btn: Add Role'}, type:'Text', defaultValue:'+ Dodaj rolę', bindable:true },
        labelBtnTempAccess: { label:{en:'Btn: Temp Access'}, type:'Text', defaultValue:'⏱ Tymczasowy dostęp', bindable:true },
        labelBtnNewRole: { label:{en:'Btn: New Role'}, type:'Text', defaultValue:'+ Nowa rola', bindable:true },
        labelBtnApply: { label:{en:'Btn: Apply'}, type:'Text', defaultValue:'Zastosuj kopię', bindable:true },
        labelBtnApplyModified: { label:{en:'Btn: Apply Modified'}, type:'Text', defaultValue:'Zastosuj ze zmianami', bindable:true },
        labelSearch: { label:{en:'Placeholder: Search'}, type:'Text', defaultValue:'Szukaj po nazwisku lub email...', bindable:true },
        labelAllRoles: { label:{en:'Label: All Roles'}, type:'Text', defaultValue:'Wszystkie role', bindable:true },
        labelNoResults: { label:{en:'Label: No Results'}, type:'Text', defaultValue:'Brak wyników', bindable:true },
        labelSuperAdmin: { label:{en:'Badge: Super Admin'}, type:'Text', defaultValue:'SA', bindable:true },
        labelVacation: { label:{en:'Badge: Vacation'}, type:'Text', defaultValue:'URLOP', bindable:true },
        labelTabRoles: { label:{en:'Tab: Roles'}, type:'Text', defaultValue:'Role i uprawnienia', bindable:true },
        labelTabVisibility: { label:{en:'Tab: Visibility'}, type:'Text', defaultValue:'Widoczność klientów', bindable:true },
        labelAssignedRoles: { label:{en:'Section: Assigned Roles'}, type:'Text', defaultValue:'Przypisane role', bindable:true },
        labelPermissions: { label:{en:'Section: Permissions'}, type:'Text', defaultValue:'Uprawnienia', bindable:true },
        labelVisibleClients: { label:{en:'Label: Visible Clients'}, type:'Text', defaultValue:'widocznych klientów', bindable:true },
        labelTempType: { label:{en:'Temp: Type'}, type:'Text', defaultValue:'Typ', bindable:true },
        labelTempRole: { label:{en:'Temp: Role'}, type:'Text', defaultValue:'Rola', bindable:true },
        labelTempDept: { label:{en:'Temp: Dept'}, type:'Text', defaultValue:'Oddział', bindable:true },
        labelTempExpires: { label:{en:'Temp: Expires'}, type:'Text', defaultValue:'Wygasa (czas polski)', bindable:true },
        labelTempReason: { label:{en:'Temp: Reason'}, type:'Text', defaultValue:'Powód (opcjonalnie)', bindable:true },
        labelTempApply: { label:{en:'Temp: Apply Btn'}, type:'Text', defaultValue:'Nadaj tymczasowy dostęp', bindable:true },
        labelAuditAllTables: { label:{en:'Audit: All Tables'}, type:'Text', defaultValue:'Wszystkie tabele', bindable:true },
        labelAuditEmailPlaceholder: { label:{en:'Audit: Email'}, type:'Text', defaultValue:'Email użytkownika...', bindable:true },
        labelConfirmDeleteRole: { label:{en:'Confirm: Delete Role'}, type:'Text', defaultValue:'Usunąć rolę "{role}"? To usunie ją od wszystkich użytkowników.', bindable:true },
        labelConfirmRemoveRole: { label:{en:'Confirm: Remove Role'}, type:'Text', defaultValue:'Usunąć rolę "{role}" użytkownikowi {user}?', bindable:true },
        labelConfirmRevoke: { label:{en:'Confirm: Revoke Grant'}, type:'Text', defaultValue:'Cofnąć tymczasowy dostęp?', bindable:true },
    }
};
